services:
  sentinel:
    user: "1000:1000"
    build:
      context: "."
      dockerfile: "Containerfile"
    image: "sentinel:${VERSION}"
    container_name: "sentinel"
    restart: "unless-stopped"
    networks:
      - "sentinel"
    env_file:
      - ".env"
    volumes:
      - "/var/data/sentinel:/data"

networks:
  sentinel:
    external: true
