services:
  sentinel:
    build:
      context: "."
      dockerfile: "Containerfile"
    image: "sentinel:0.1.20"
    container_name: "sentinel"
    restart: "unless-stopped"
    networks:
      - "sentinel"
    env_file:
      - ".env"
    volumes:
      - "/var/data/sentinel:/data"
    entrypoint: [ "uv", "run", "/app/src/main.py" ]

networks:
  sentinel:
    external: true
