services:
  sentinel:
    build:
      context: .
    image: sentinel:0.1.18
    container_name: sentinel
    restart: unless-stopped
    networks:
      - int
    env_file:
      - .env
    volumes:
      - /var/data/sentinel:/data
    entrypoint: [ "uv", "run", "/app/src/main.py" ]

networks:
  int:
    external: true
