[project]
name = "sentinel"
version = "0.1.21"
requires-python = ">=3.13"
dependencies = [
  "cordhook @ git+https://github.com/tainn/cordhook.git@0.2.10",
  "httpx==0.28.1",
  "beautifulsoup4==4.13.4"
]

[tool.ruff]
fix = true
indent-width = 4
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "N",
  "UP",
  "ANN",
  "B",
  "A",
  "ICN",
  "PIE",
  "Q",
  "RSE",
  "RET",
  "SIM",
  "ARG",
  "PTH"
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.format]
preview = true
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = false
docstring-code-format = true
